version: "3"
services:
    app:
        build:
            context: .
        ports:
            - "${APP_PORT:-8000}:8000"
        env_file:
            - ./.env
        environment:
            LARAVEL_SAIL: 1
